services:
  - type: web
    name: gitlab-analysis
    env: python
    buildCommand: |
      curl -sSL https://github.com/returntocorp/semgrep/releases/download/v1.96.0/semgrep-v1.96.0-ubuntu-20.04.tgz -o semgrep.tgz
      tar -xzf semgrep.tgz
      sudo mv semgrep /usr/local/bin/
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PATH
        value: /usr/local/bin:${PATH}