services:
  - type: web
    name: gitlab-scanner
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker asgi_app:asgi_app -c gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        sync: false
      - key: GITLAB_CLIENT_ID
        sync: false
      - key: GITLAB_CLIENT_SECRET
        sync: false
      - key: GITLAB_REDIRECT_URI
        sync: false
    healthCheckPath: /health
    autoDeploy: true