services:
  - type: web
    name: Maestro
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m pip install semgrep
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0